import type { PublicSettings, Settings } from './types'

export const SETTINGS_KEYS = [
  'site_title',
  'site_title_color',
  'site_title_font_size',
  'site_title_effect',
  'marquee',
  'theme_preset_id',
  'public_mode',
  'browser_sync_enabled',
  'theme',
  'background_preset_id',
  'background',
  'backgrounds',
  'custom_css',
  'custom_js',
  'image_host_url',
  'search_engine',
  'card_size',
  'card_style',
  'card_icon_size',
  'card_show_description',
  'card_description_mode',
  'card_background_color',
  'card_background_opacity',
  'card_icon_show_title',
  'card_text_color',
  'search_box_show',
  'search_engine_selector_show',
  'content_layout',
  'navigation',
  'footer_html',
  'most_visited_count',
  'site_title_show',
  'custom_themes',
] as const satisfies readonly (keyof Settings)[]

export const PUBLIC_SETTINGS_KEYS = [
  'site_title',
  'site_title_color',
  'site_title_font_size',
  'site_title_effect',
  'marquee',
  'theme_preset_id',
  'theme',
  'background_preset_id',
  'background',
  'backgrounds',
  'search_engine',
  'image_host_url',
  'card_size',
  'card_style',
  'card_icon_size',
  'card_show_description',
  'card_description_mode',
  'card_background_color',
  'card_background_opacity',
  'card_icon_show_title',
  'card_text_color',
  'search_box_show',
  'search_engine_selector_show',
  'content_layout',
  'navigation',
  'footer_html',
  'custom_css',
  'custom_js',
  'most_visited_count',
  'site_title_show',
  'custom_themes',
] as const satisfies readonly (keyof PublicSettings)[]

export const PUBLIC_DATA_SETTINGS_KEYS = [
  'public_mode',
  ...PUBLIC_SETTINGS_KEYS,
] as const satisfies readonly (keyof Settings)[]

export function toPublicSettings(settings: Settings): PublicSettings {
  return {
    site_title: settings.site_title,
    site_title_color: settings.site_title_color,
    site_title_font_size: settings.site_title_font_size,
    site_title_effect: settings.site_title_effect,
    marquee: settings.marquee,
    theme_preset_id: settings.theme_preset_id,
    theme: settings.theme,
    background_preset_id: settings.background_preset_id,
    background: settings.background,
    backgrounds: settings.backgrounds,
    search_engine: settings.search_engine,
    image_host_url: settings.image_host_url,
    card_size: settings.card_size,
    card_style: settings.card_style,
    card_icon_size: settings.card_icon_size,
    card_show_description: settings.card_show_description,
    card_description_mode: settings.card_description_mode,
    card_background_color: settings.card_background_color,
    card_background_opacity: settings.card_background_opacity,
    card_icon_show_title: settings.card_icon_show_title,
    card_text_color: settings.card_text_color,
    search_box_show: settings.search_box_show,
    search_engine_selector_show: settings.search_engine_selector_show,
    content_layout: settings.content_layout,
    navigation: settings.navigation,
    footer_html: settings.footer_html,
    custom_css: settings.custom_css,
    custom_js: settings.custom_js,
    most_visited_count: settings.most_visited_count,
    site_title_show: settings.site_title_show,
    custom_themes: settings.custom_themes,
  }
}
